version: '3.3'
services:
  postgres:
    container_name: coffeeshop_container
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER= user
      - POSTGRES_PASSWORD=2easy2forget
      - POSTGRES_DB=coffeeshop_db
    volumes:
      - 'pg-data:/var/lib/postgresql'
    ports:
      - '5432:5432'
volumes:
  pg-data:
